# Айди аирдропа
airdrop1:
  # Дискорд вебхук
  webhook: ""

  airDropStartMessage:
    # Содержимое сообщения
    content: ""
    embed:
      # Заголовок эмбеда
      title: "airdrop1"
      # Описание эмбеда
      # Вместо \n используйте \\n
      description: "Аирдроп заспавнился!\\n \\n
        Координаты:\\n
        {x}\\n
        {y}\\n
        {z}\\n"
      # Цвет эмбеда
      color: 20E9B0

# Айди аирдропа
airdrop2:
  # Дискорд вебхук
  webhook: ""

  airDropStartMessage:
    # Содержимое сообщения
    content: ""
    embed:
      # Заголовок эмбеда
      title: "airdrop2"
      # Описание эмбеда
      # Вместо \n используйте \\n
      description: "Аирдроп заспавнился!\\n \\n
        Координаты:\\n
        {x}\\n
        {y}\\n
        {z}\\n"
      # Цвет эмбеда
      color: 20E9B0